### ISSUE TITLE
크로미움 기반 브라우저의 확장프로그램 설치 관련

### ISSUE THREAD

**Issue by moxbt** [Entry-DevTools/EntryDevTools#3]
크롬 웹 스토어에 올리려면 유료이기 때문에 일부러 Zip 파일을 다운로드 받아 설치하라고 하신 것 같은데,
웨일 스토어에서는 네이버 계정으로 로그인하고 본인인증만 하면 무료로 프로그램을 올릴 수 있습니다.
웨일 프로그램도 whale.~~ 뿐만 아니라 chrome.~~도 작동하니
웨일 스토어에 올리셔도 좋을 것 같아요 :)

**Comment by dn1t** [comment]
사실 최초 버전 출시 당시 올리려고 했는데, 스크린샷 올리는게 너무 귀찮아서 ㅠㅠ

**Comment by moxbt** [comment]
> 사실 최초 버전 출시 당시 올리려고 했는데, 스크린샷 올리는게 너무 귀찮아서 ㅠㅠ

히익 귀찮았다니 ㄷ
